services:
  openkb:
    container_name: ${OPENKB_CONTAINER_NAME:-openkb_app}
    image: ${OPENKB_IMAGE_NAME:-wachiwi/openkb}:${OPENKB_IMAGE_VERSION:-latest}
    restart: ${RESTART_POLICY:-always}
    environment:
      - TZ=${TIMEZONE:-Asia/Bangkok}
    ports:
      - ${OPENKB_HTTP_PORT:-4444}:4444
    volumes:
      - default:/var/openKB/data
    networks:
      - default
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:4444"]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-10s}
      retries: ${HEALTHCHECK_RETRIES:-3}

networks:
  default:
    name: openkb_network
    driver: bridge

volumes:
  default:
    name: openkb_data
    driver: local