services:
  openkb:
    container_name: ${OPENKB_CONTAINER_NAME}
    image: ${OPENKB_IMAGE_NAME}:${OPENKB_IMAGE_VERSION}
    restart: ${RESTART_POLICY}
    environment:
      - TZ=${TIMEZONE}
    ports:
      - ${OPENKB_HTTP_PORT}:4444
    volumes:
      - default:/var/openKB/data
    networks:
      - default
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:4444"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}

networks:
  default:
    name: ${OPENKB_CONTAINER_NAME}_network
    driver: bridge

volumes:
  default:
    name: ${OPENKB_CONTAINER_NAME}_data
    driver: local