version: '3.9'
services:
  web:
    image: wachiwi/openkb:latest
    container_name: openkb
    restart: always
    ports:
      - ${APP_PORT}:4444
    networks:
      - default
    volumes:
      - ./data:/var/openKB/data

networks:
  default:
    name: docker_openkb_network
    driver: bridge

volumes:
  data:
    name: docker_openkb_data
    driver: local
