version: '3.9'
services:
  web:
    image: wachiwi/openkb:latest
    container_name: openkb
    restart: always
    ports:
      - ${APP_PORT}:4444
    networks:
      - default
    volumes:
      - data:/data
      - /var/lib/openKB:/var/openKB/data

networks:
  default:
    driver: bridge

volumes:
  data:
    driver: local
